# .github/workflows/veille.yml
name: Lancer la veille d'informations

on:
  # Se lance toutes les heures
  schedule:
    - cron: '0 * * * *'
  # Permet de le lancer manuellement depuis l'onglet Actions de GitHub
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupère le code du dépôt
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Installe Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3. Installe les dépendances du script
      - name: Install dependencies
        run: npm install

      # 4. Lance le script de veille
      - name: Run scraper
        run: node scraper.js

      # 5. Commit et Push le fichier veille.json mis à jour
      # Cette action va automatiquement commiter les changements dans le dépôt
      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Mise à jour automatique des données de veille'
          file_pattern: 'public/veille.json'