name: Lancer la veille d'informations

on:
  schedule:
    - cron: '*/120 * * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # NOUVELLE MÉTHODE : On utilise une action dédiée pour installer Chrome
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: setup-chrome # On donne un ID à l'étape pour utiliser son résultat

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run scraper
        run: node scraper.js
        env:
          # On indique à Puppeteer où trouver le Chrome qui vient d'être installé
          PUPPETEER_EXECUTABLE_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
          ONESIGNAL_APP_ID: ${{ secrets.ONESIGNAL_APP_ID }}
          ONESIGNAL_REST_API_KEY: ${{ secrets.ONESIGNAL_REST_API_KEY }}

      - name: Commit and push if it changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'Mise à jour automatique des données de veille'
          file_pattern: 'public/veille.json'
